### ISSUE TITLE
ImportError: No module named gui

### ISSUE THREAD

**Issue by vitormhenrique** [pimoroni/python-multitouch#1]
Hello,

I'm getting an issue "ImportError: No module named gui" when trying to run the example, which modules do I need to install to get this driver working?

**Comment by Gadgetoid** [comment]
You don't need the `gui` module to use the touch driver itself, but I use it in most (if not all) of the examples. Install it by navigating into the `gui` folder and running:

`sudo python setup.py install`

**Comment by iball** [comment]
Installed it and get:

Traceback (most recent call last):
  File "./touchtest.py", line 1, in <module>
    from ft5406 import Touchscreen, TS_PRESS, TS_RELEASE, TS_MOVE
ImportError: No module named ft5406

**Comment by iball** [comment]
Also getting this one after making sure ft5406.py is in the same directory as my code since it seems the install didn't work(?):

Traceback (most recent call last):
  File "./touchtest.py", line 1, in <module>
    from ft5406 import Touchscreen, TS_PRESS, TS_RELEASE, TS_MOVE
  File "/home/pi/ft5406.py", line 10, in <module>
    import queue
ImportError: No module named queue

**Comment by iball** [comment]
Fixed it.  It should be "Queue" instead of "queue" in the ft5406.py file.

**Comment by Gadgetoid** [comment]
Ah yes that would be a Python 2 vs Python 3 idiosyncrasy. I should probably fix that.
