### ISSUE TITLE
Update touchscreen event name

### ISSUE THREAD

**Issue by rogueturnip** [pimoroni/python-multitouch#2]
The check is limited right now. It would be useful to take this as a value in the call so it can be more generic.

**Comment by Gadgetoid** [comment]
Agreed! I've added a new argument to the `Touchscreen()` constructor; `device`.

```python
ts = Touchscreen(device="Touch Device Name")
```

I should probably move to rename the library from `ft5406`, since it implements multi-touch to spec and should be compatible with most multi-point touch displays.
