### ISSUE TITLE
change pygame.event loop

### ISSUE THREAD

**Issue by rogueturnip** [pimoroni/python-multitouch#3]
I've been going through the examples and it's still escaping me how to change from the pygame tslib event reading over to the ft5406.

My use is pretty simple, I just want to capture touch events (press right now but motion later) so I an pass the x,y coordinates to check for a collision with a sprite.

Do I need to change more than just adding in the for touch in ts.loop()?

**Comment by Gadgetoid** [comment]
Did you have any luck with this?

Generally the `for touch in ts.poll()` can supplement your event loop and you can use touch.x and touch.y, but it depends how your code looks.

https://github.com/pimoroni/python-multitouch/blob/0cb6e61c412b833d27df5dadabd53c1e330fdd0c/examples/lines.py#L23-L31
