### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by dannyconstantine** [pimoroni/python-multitouch#4]
I followed all the steps and installed everything.
when I run my python app I get this
$ sudo python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from ft5406 import Touchscreen, TS_PRESS
  File "/home/pi/ft5406.py", line 19, in <module>
ImportError: No module named queue

Also when I run the following command
$ dmesg | grep -i ft5406
[    3.987815] rpi-ft5406 rpi_ft5406: Probing device
[    4.027597] input: FT5406 memory based driver as /devices/virtual/input/input2

**Comment by Gadgetoid** [comment]
You'll have to run it with `python3`, this library wasn't written with Python 2.x support.
