### ISSUE TITLE
After latest Pi update ft5406 driver reports RuntimeError: Unable to locate touchscreen device

### ISSUE THREAD

**Issue by MicroDoser** [pimoroni/python-multitouch#7]
After latest upgrade ft5406.py raises 'RuntimeError: Unable to locate touchscreen device'

To replicate: download PiOs, update to latest version, download ft5406.py, make python file containing 'using events' test code, run file using python 3 in Thonny

error raised by line: self._f_device = io.open(self._touch_device(), 'rb', self.EVENT_SIZE)

Tested on different machines and different screens.

**Comment by Gadgetoid** [comment]
Which touchscreen are you using?

Presumably the name has changed, albeit I don't know why that would happen. This new update is blindsiding me with a few quirks.

The original device name for the official touchscreen is "FT5406 memory based driver", you'll have to figure out what the new one is.

I think you can do that with `xinput list`  (you may need to prefix that with `DISPLAY=:0.0`) or `cat /proc/bus/input/devices` or check the output of `dmesg` for `rpi-ft5406` and `input`.

**Comment by MicroDoser** [comment]
I am using the official 7" touchscreen. As a workaround, I will use a .img taken from before the change.

I'll have a look in the driver code and see what I can figure out.

"I think you can do that with xinput list (you may need to prefix that with DISPLAY=:0.0) or cat /proc/bus/input/devices or check the output of dmesg for rpi-ft5406 and input."

Thanks for the pointer, I will see if I can get something working. If I can, I will submit a pull request.

**Comment by project-owner** [comment]
The new name is 'raspberrypi-ts'. It works if I just change the name:
TOUCHSCREEN_EVDEV_NAME = 'raspberrypi-ts'
#TOUCHSCREEN_EVDEV_NAME = 'FT5406 memory based driver'

**Comment by Gadgetoid** [comment]
Thank you!

I'm surprised anyone still uses this junk. I wonder if I could add the old/new EVDEV_NAME so it will auto find the touchscreen either way.

**Comment by MicroDoser** [comment]
> 
> 
> Thank you!
> 
> I'm surprised anyone still uses this junk. I wonder if I could add the old/new EVDEV_NAME so it will auto find the touchscreen either way.

If you know of a driver which I could use for the official 7" touchscreen which would be less 'junk', I would be interested in having a look at it. I found this years ago and, as it carried on working, never looked at drivers for the touchscreen again ;)

**Comment by Gadgetoid** [comment]
Haha! I can't say that I do- which is why I threw this together. Glad people are getting some use out of it!

**Comment by MicroDoser** [comment]
When I last had a look around, this was the easiest way to get the full 10 touch support on the official touchscreen. The other methods I checked out were more 'junk' than this by a large degree (either far more cryptic or with much less functionality) I suspect that might not have changed. Thanks for throwing it together.

**Comment by 3JL** [comment]
> The new name is 'raspberrypi-ts'. It works if I just change the name:
> TOUCHSCREEN_EVDEV_NAME = 'raspberrypi-ts'
> #TOUCHSCREEN_EVDEV_NAME = 'FT5406 memory based driver'

Worked for me as well! 👍

**Comment by drawk-cab** [comment]
Changing the name to `raspberrypi-ts` worked for me too.
It seems that pygame relies on X to calibrate the touch screen for it, so if you're running a console pygame then its built in touch funcitons get the positions all wrong. I don't need all 10 touches but I definitely want them to be in the right place!

**Comment by huasheng-yue** [comment]
thank you for your share......even it is not run in windows10+anaconda............?

**Comment by huasheng-yue** [comment]
thank you for your share......even it is not run in windows10+anaconda............?
